apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
  namespace: oficina
  labels:
    app: oficina-app
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  DB_URL: "jdbc:postgresql://oficina-postgres:5432/oficina_mecanica"
  DB_USERNAME: "oficina"
  JWT_EXPIRATION: "86400000"
  MAIL_HOST: "oficina-mailhog"
  MAIL_PORT: "1025"
  MAIL_ENABLED: "true"
  MAIL_FROM: "noreply@oficina.com"
