apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-mailhog
  namespace: oficina
  labels:
    app: oficina-mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oficina-mailhog
  template:
    metadata:
      labels:
        app: oficina-mailhog
    spec:
      containers:
        - name: mailhog
          image: mailhog/mailhog:v1.0.1
          ports:
            - containerPort: 1025
              name: smtp
            - containerPort: 8025
              name: ui
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: oficina-mailhog
  namespace: oficina
spec:
  type: ClusterIP
  selector:
    app: oficina-mailhog
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: ui
      port: 8025
      targetPort: 8025
