apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
  namespace: oficina
  labels:
    app: oficina-app
type: Opaque
stringData:
  # Em produção, use Sealed Secrets / External Secrets / CI para injetar valores reais
  DB_PASSWORD: "oficina123"
  JWT_SECRET: "mude-esta-chave-em-producao-use-minimo-32-caracteres"
  MAIL_STATUS_TOKEN: "oficina-email-status-token"
  POSTGRES_PASSWORD: "oficina123"
